### PR TITLE
Added Vercel Deployment.

### PR DESCRIPTION
**Pull request by sekiryl**

### CODE REVIEW

**Comment by lewisdoesstuff** [comment]
Thanks for this!  

I haven't used Vercel before - how does it deal with secrets in the config? OpenWeatherMap keys shouldn't _really_ be in the config uploaded to the repo

**Comment by sekiryl** [comment]
> Thanks for this!
> 
> I haven't used Vercel before - how does it deal with secrets in the config? OpenWeatherMap keys shouldn't _really_ be in the config uploaded to the repo

It works just like github pages. But, you don't need to use `actions` because it have `Vue.js` preset built in.

It is also faster than github actions, For me it takes less than 10 seconds to build after pushing any changes to repository whereas, github actions take more than 30 seconds.

You  can also use custom domains for your deployment.

Why don't you try using it yourself once? It will give you a better idea.

**Comment by lewisdoesstuff** [comment]
Personally don't have a use case for it, but sounds good! 

Merged :)

**Comment by sekiryl** [comment]
Thanks! I forgot to add it in development part, You can add it if you want.

**Pull request merged**
